name: Test Patches

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/_setup.yml

  unit-tests:
    needs: setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image for Testing
        id: build
        uses: docker/build-push-action@v5
        with:
          target: patched
          context: .
          platforms: linux/${{ matrix.arch.suffix }}
          pull: true
          load: true
          provenance: false
          build-args: |
            KUBE_VERSION=${{ matrix.kube-version.version }}
            KUBE_VERSION_GO=${{ matrix.kube-version.go }}
          cache-from: type=gha,scope=patched-${{ matrix.kube-version.version }}-${{ matrix.arch.suffix }}
          cache-to: type=gha,mode=max,scope=patched-${{ matrix.kube-version.version }}-${{ matrix.arch.suffix }}

      - name: Run Unit Tests
        run: |
          docker run --rm \
            ${{ steps.build.outputs.imageid }} \
            CGO_ENABLED=1 make test
